In [22]:
import torch
import torch.nn as nn

In [35]:
torch.manual_seed(4.2)
inputs=torch.tensor([1.0,2.0,3.0])

In [24]:
neuron=nn.Linear(in_features=3,out_features=1) 

In [25]:
output=neuron(inputs)

In [26]:
output

tensor([-0.5479], grad_fn=<ViewBackward0>)

In [27]:
neuron.weight

Parameter containing:
tensor([[-0.0737, -0.0594, -0.1965]], requires_grad=True)

In [28]:
neuron.bias

Parameter containing:
tensor([0.2342], requires_grad=True)

In [34]:
neuron.weight @ inputs+neuron.bias

tensor([-0.5479], grad_fn=<AddBackward0>)